### ISSUE TITLE
Latest wheel==0.32.0 breaks auditwheel/wheeltools.py

### ISSUE THREAD

**Issue by hugovk** [pypa/auditwheel#102]
Wheel 0.32.0 was released two days ago and has refactored its (private) API, breaking `auditwheel`:

```
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/main_repair.py", line 43, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/repair.py", line 13, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.6.6/lib/python3.6/site-packages/auditwheel/wheeltools.py", line 14, in <module>
    from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
ImportError: cannot import name 'open_for_csv'
```
https://travis-ci.org/python-pillow/pillow-wheels/jobs/435427307#L4860

The same thing hit multibuild and delocate: https://github.com/pypa/wheel/issues/255.

Note that wheel officially has no public API:

> It should be noted that wheel is not intended to be used as a library, and as such there is no stable, public API.

https://github.com/pypa/wheel/issues/255

(We're working around the issue by pinning to the previous wheel==0.31.1.)

**Comment by agronholm** [comment]
I had no idea that so many tools relied on the private API of wheel. This is a bummer.

**Comment by hugovk** [comment]
Yep. A lot of duplicates, but 32k results for this one:

https://github.com/search?l=Python&q="from+wheel.util+import"+open_for_csv&type=Code

People in general don't read docs. Perhaps using the `_underscore` convention would be more clear (but would apply to everything, and break all third-party use.)

**Comment by matthew-brett** [comment]
Dammit - it is unfortunate that Robert copied the delocate wheel code without the tests.  That makes it much harder to know if the fixes are going to work.

I've just fixed this in the latest delocate release.  Maybe auditwheel can import from delocate?

**Comment by rmcgibbo** [comment]
Sorry :/

**Comment by Mizux** [comment]
My 2 cents, in docker image `auditwheel` program didn't work anymore so I use:
```shell
/opt/_internal/cpython-3.6.6/bin/python -m pip install wheel=0.31.1
```

**Comment by Mizux** [comment]
@matthew-brett I use this workaround yesterday (Paris Time ~ 15h ago) to generate our python ortools packages....
I should try again today without this patch and using your last docker image...

ps: here the patch https://github.com/google/or-tools/commit/c907c5730586422dfa699c14685d3a9aac7ea40f
and here the dockerfile use: https://github.com/google/or-tools/blob/master/tools/docker/manylinux1.Dockerfile

**Comment by matthew-brett** [comment]
Sounds reasonable to me.

**Comment by ehashman** [comment]
We have all these wacky helpers defined for being able to treat a wheel as a context. Unclear if that's the sort of thing that should go into a public API but @agronholm I will take a deep look and update that issue when I'm done.

**Comment by ehashman** [comment]
Ah, great. Emphatic +1.

There's a PyPA sprint next weekend, I'd be very interested in looking at this then.

**Comment by anthrotype** [comment]
is anybody working on this? I'm at the PyPA sprint in London and could work on updating auditwheel to work with wheel 0.32

**Comment by matthew-brett** [comment]
@ehashman - are you at the sprint?  @anthrotype - I'm sure you saw the stuff above - if it were me, I'd check that the delocate code does what's needed, and depend on that, because it has tests, and it would mean only one place to maintain the code (Robert C copied it from delocate originally).

**Comment by matthew-brett** [comment]
Or even break that part of the code out into its own tiny module.  Maybe that would make it easier for Wheel to know what they need to keep stable in the API.

**Comment by anthrotype** [comment]
I'm not sure if @ehashman is here in London or will be in New York (don't think they've started there yet).

> depend on that, because it has tests

I agree, that'd probably be much better than copy-paste each other. 

>  break that part of the code out into its own tiny module

@matthew-brett do you mean the delocate/wheeltools.py module, right?

**Comment by matthew-brett** [comment]
Hi - yes - the wheeltools module, but it also imports from other modules, that you'll recognize, if you look at the two code-bases.

**Comment by anthrotype** [comment]
I can work on that. Would you like to create a `wheeltools` github repository with your username and add me as collaborator? I can push my work there, and if @ehashman likes can also join in later when they start in New York

**Comment by anthrotype** [comment]
shall I also copy that `tmpdirs.py` module into this new `wheeltools` package? Both delocate and auditwheel are using it. Maybe it's fine that both keep vendoring their own copy for now, I'll just do delocate/wheeltools.py and delocate/tools.py

**Comment by anthrotype** [comment]
I started here https://github.com/anthrotype/wheeltools

Now I’m off to lunch, I’ll continue in the afternoon

**Comment by ehashman** [comment]
Hey all, I'll be at the NYC sprints, just woke up. Will catch up on this once I arrive!

**Comment by matthew-brett** [comment]
I'm on Google chat if y'all need me - matthew.brett@gmail.com .  

Yes, definitely add the unit tests.

I think the multibuild submodule doesn't need to be in the new repo, but the plan is to make a new pypi-installable package to do the wheel stuff.  Then delocate and auditwheel would import that..  For delocate I have some test wheels with extension code in there, but we could make small pure python test wheels for the tests, or use the one I'm building in delocate.

**Comment by anthrotype** [comment]
We can remove multibuild, sure. I only added it to reuse the same Travis setup and ensure the existing delocate tests are still working (they do now).
I’m off for today. I think I added both @matthew-brett and @ehashman as collaborators. 
You can take over from here.

**Comment by anthrotype** [comment]
I have removed multibuild as well as the functions in wheeltools/tools.py that are only required by delocate and hence are macOS-specific (e.g. those that use otool and install_name_tool commands).

What we need to do now is:
1) check whether the wheeltools module that is vendored in auditwheel has diverged from the upstream delocate/wheeltools, and if so integrate any changes into the standalone wheeltools package.
2) publish wheeltools to PyPI (the travis setup is configured to automatically upload on tagged commits, using my PyPI encrypted credentials). 
2) update auditwheel and delocate to import from the new wheeltools module.

**Comment by anthrotype** [comment]
I have put up the scaffolding of a stand-alone `wheeltools` module, by extracting the wheeltools.py and tools.py modules (and respective unit tests) from the current delocate master branch.
I've also verified that rest of the delocate test suite passes when importing from the standalone module (https://github.com/matthew-brett/delocate/pull/46).

I then tried to take this wheeltools module extracted from delocate and import it inside auditwheel, however I stumbled on a few issues and am not sure how (or whether) to proceed.

The `wheeltools.add_platforms` function in particular has significantly diverged between delocate and auditwheel:
1) In delocate, it takes the wheel filename as input, whereas in the latter it takes an already open `InWheelCtx` object.
2) the auditwheel `add_platforms` has an additional `remove_platforms` keyword argument, which the delocate version lacks (in fact, the function name is `add_platforms`, which suggests that it only extends the list of platforms).
3) delocate raises an error `"Cannot add platforms to pure wheel"` when the "Root-Is-Purelib" whereas (see the recent https://github.com/pypa/auditwheel/pull/110), auditwheel also checks for binaries inside a purelib root, or ignores the pure wheel without raising an error.
4) auditwheel has some informative print() statements, whereas the delocate version does not (#109) 

There may be more differences which I'm not aware of yet. I have to say, I'm not familiar enough with the Wheel specification; also am busy with other things, and am not sure I can promise to continue working on this in the coming weeks.
I guess I underestimated the amount of work needed (I should have checked with you guys before embarking on it). Anyway, I hope @ehashman and @matthew-brett will continue from where I left and that this effort of mine was not completely wasted. :)

**Comment by lkollar** [comment]
Closing this as work on `wheeltools` seems to have stopped and `wheel` has been upgraded to 0.34 in https://github.com/pypa/auditwheel/pull/223, so the original issue is fixed.

@anthrotype feel free to open a new issue if/when you think `wheeltools` can replace the vendored version.
