### ISSUE TITLE
Drop the dot when invoking pytest

### ISSUE THREAD

**Issue by jaraco** [pypa/auditwheel#111]
PyTest [recommends](https://github.com/pytest-dev/pytest/issues/1629) using `pytest` instead of `py.test`. This project should adopt that pattern in its test invocations [such as here](https://github.com/pypa/auditwheel/blob/5a56bca4f416bd069ecc03c418311c488b494f2f/tox.ini#L9).

I'm at the Bloomberg PyPA sprint and overheard 'py dot test', so thought I'd capture this trivial issue.

**Comment by kaikulimu** [comment]
Hi, I will work on this.

**Comment by kaikulimu** [comment]
Hi, I will work on this.

**Comment by kaikulimu** [comment]
Submitted PR: https://github.com/pypa/auditwheel/pull/112

**Comment by ehashman** [comment]
Closed via #112.

**Comment by jaraco** [comment]
Woo hoo. Thanks!
