### ISSUE TITLE
Fix continuous deployment

### ISSUE THREAD

**Issue by ehashman** [pypa/auditwheel#114]
It appears the credentials in the `.travis.yml` secure section don't work, we got a 403 error in the latest attempt at deployment: https://travis-ci.org/pypa/auditwheel/jobs/447196655

I'll deploy 1.10rc1 manually.

**Comment by atombrella** [comment]
The shell script also has a bunch of issues. The wheel house URL `http://stanford.edu/~rmcgibbo/wheelhouse/`returns a 404.

**Comment by ehashman** [comment]
I've just given up on this and disabled it. See #128.
