### ISSUE TITLE
2.0 consumes metapackages

### ISSUE THREAD

**Issue by thewtex** [pypa/auditwheel#138]
auditwheel 2, when applied to a metapackage, i.e. a package that just has dependencies and no modules or libraries, consumes the wheel. That is, when executed on the *linux*.whl file, the file is removed, but no *manylinux*.whl is produced. 1.X produced the *manylinux* wheel.

**Comment by ehashman** [comment]
Can you point me to a specific package to test this behaviour?

When you say 1.x, did you test with 1.10 or an earlier release?

**Comment by thewtex** [comment]
This is the package:

  https://github.com/InsightSoftwareConsortium/ITKPythonPackage

but it is admittedly a beast to build (that's why the binaries are so nice ;-) ).

As a current workaround, we pin to auditwheel 1.9.0.

**Comment by lkollar** [comment]
I don't think this is an issue anymore. @thewtex if you still encounter this with the latest auditwheel, please reopen it with a reproducer.
