### ISSUE TITLE
Missing library error from repaired wheel

### ISSUE THREAD

**Issue by matthew-brett** [pypa/auditwheel#14]
I'm sorry not to have done a better job of debugging this but ..

I'm trying to build h5py wheels.

I think I correctly built and repaired the wheel, and it installs and tests OK on a Debian sid machine I have.

However, when I test the wheel on the docker image itself, I get:

```
python -c 'import h5py; h5py.run_tests()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/3.4.4/lib/python3.4/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: libsz.so.2: cannot open shared object file: No such file or directory
```

Script to generate hdf5 and libsz libraries:  https://gist.github.com/9279c5c368d61118cf1c
Script to build h5py wheel : https://gist.github.com/matthew-brett/0dbd3747cbd76ea8ca49
Unfixed wheel : http://nipy.bic.berkeley.edu/scipy_installers/tmp/unfixed/h5py-2.4.0-cp34-cp34m-linux_x86_64.whl
Fixed wheel : http://nipy.bic.berkeley.edu/scipy_installers/tmp/fixed/h5py-2.4.0-cp34-cp34m-linux_x86_64.whl
Script to run wheel test : https://gist.github.com/41eaad61fbf02072b2ba

`libsz.so.2` is in the `.libs` directory of the h5py install, and rpath for the `_errors` extension does contain `$ORIGIN/.libs`.

**Comment by rmcgibbo** [comment]
I'll take a look.

**Comment by rmcgibbo** [comment]
I can reproduce this, and I'm not quite sure what's going on yet, but I think I can have a fix soon.
