### ISSUE TITLE
Wheelhouse is 404

### ISSUE THREAD

**Issue by di** [pypa/auditwheel#142]
The `WHEELHOUSE=1` Travis test currently tries to fetch wheelhouse from https://github.com/getnikola/wheelhouse/archive/v2.7.zip, however this link is 404 and the repo is missing as well: https://github.com/getnikola/wheelhouse

This test is currently an allowed failure, do we need it? Do we need to update the URL for wheelhouse?

**Comment by ehashman** [comment]
The PRs you'd want for context are here: #86 #87

If someone wants to update this test to make it stop failing, I'd be happy to review. We'd need to swap out the nonexistent wheelhouses with ones that are still live.

**Comment by lkollar** [comment]
The tests have been removed in #179.
