### ISSUE TITLE
Repair can produce an invalid manylinux1 wheel

### ISSUE THREAD

**Issue by takluyver** [pypa/auditwheel#146]
I'm experimenting with building manylinux2010 wheels for pygame, to test the toolchain. `auditwheel repair` (with no `--plat`) argument tags the wheel `manylinux1`. But then re-running auditwheel on that wheel, it is not valid for manylinux1:

- `auditwheel show` says "This constrains the platform tag to "manylinux2010_x86_64". In order
to achieve a more compatible tag, you would need..."
- `auditwheel repair` on the already-repaired wheel says:

> cannot repair "wheelhouse/pygame-2.0.0.dev0-cp37-cp37m-manylinux1_x86_64.whl" to "manylinux1_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.

I understand that it's necessary to specify the tag manually at the command line, but it shouldn't successfully apply the `manylinux1` tag if the wheel is not `manylinux1` compatible.

Educated guesswork: I think it checks the validity of the tag based on the files already in the wheel. These are presumably valid for manylinux1. But then it grafts some libraries into the wheel, and these make it invalid.

**Comment by jjhelmus** [comment]
@takluyver Would it be possible to provide the pygame wheel so that anyone (me included) who wanted to debug this issue would have something to test with?

**Comment by takluyver** [comment]
Of course. Though because it's tricky to run auditwheel the first time without the libraries it's built against, maybe it's easier if I push my work into a branch and point you to that?

I'm also investigating a partial fix, but more eyes on it are definitely welcome. :slightly_smiling_face:

**Comment by takluyver** [comment]
OK, the branch is [here](https://github.com/takluyver/pygame/tree/manylinux2010). The last commit works around this issue, but if you step back to https://github.com/takluyver/pygame/commit/61c381b8f72cafc1f9ba555cca9ad149d62997cc you should be able to reproduce it.

From the repo root:

```
cd buildconfig/manylinux-build
make base-image-x64
make wheels-x64
```

**Comment by takluyver** [comment]
#148 is a partial fix - it makes auditwheel error after producing the wheel. I've tested this on the pygame wheels. That's all the time I've got to dig into this today, so if you want to work on a proper fix, go for it.
