### ISSUE TITLE
Auditwheel needs a new maintainer or maintainers

### ISSUE THREAD

**Issue by njsmith** [pypa/auditwheel#149]
@ehashman is stepping down as auditwheel maintainer: https://hashman.ca/leaving-pypa/

Thank you Elana!

Now we need a new maintainer (or better yet: maintainers). Anyone interested?

**Comment by njsmith** [comment]
[On Twitter](https://twitter.com/auvipy/status/1116210323944382464), @auvipy expressed some interest.

**Comment by auvipy** [comment]
yes

**Comment by takluyver** [comment]
I may be able to do some bits of maintenance, and this is an area I'd like to understand better. But I probably don't have time to commit to being the main maintainer of auditwheel.

**Comment by lkollar** [comment]
I'm interested in helping out too.

**Comment by njsmith** [comment]
I'm guessing that @mayeut might be interested too, given that he reviewed #155 and has been working on the docker image. So I'm counting 4 potential maintainers (@auvipy, @takluyver, @lkollar, @mayeut).

I think @takluyver and @mayeut both have permissions already. @auvipy is an experienced OSS dev (e.g. on the core team for Celery). I just talked to @lkollar at PyCon; he doesn't have as much OSS experience, but @pganssle and @pablogsal have worked with him at Bloomberg and vouch for him.

My suggestion: the four of you join together to form an auditwheel-maintaining team. Sound good?

**Comment by njsmith** [comment]
@rmcgibbo Hey Robert, it looks like you're the only one who can modify the permissions for auditwheel on PyPI. Could you add someone else as an "owner", in case you're not available sometime?

**Comment by rmcgibbo** [comment]
Done. I changed everyone who was currently "maintainer" over to "owner". (You, Elana, Olivier). I probably ought to remove myself as well, but the UI option in Warehouse for that seems greyed out.

**Comment by auvipy** [comment]
It would be great to learn and help to improve auditwheel and wheel :) I will increase my contributions to pypa packages as much as I can after my celery project works :)

**Comment by auvipy** [comment]
I have been invited to join and I accepted it. I can recall the memory 3 years ago in May I was invited to maintain django-celery project and later was promoted as a core dev for my contributions. I am really honored. Thanks :)

**Comment by njsmith** [comment]
> Done. I changed everyone who was currently "maintainer" over to "owner". (You, Elana, Olivier). I probably ought to remove myself as well, but the UI option in Warehouse for that seems greyed out.

Whoops, only just saw this. I removed Robert, as per his request, and added takowl (= @takluyver), since he's the only one here whose PyPI name I know off the top of my head :-). Thomas, are you up to handling it from here?

**Comment by takluyver** [comment]
Thanks! Yes, I can add the others.

@auvipy @lkollar @mayeut : if you want to confirm your PyPI username for me, I'll give you access to publish releases.

**Comment by lkollar** [comment]
Mine is lkollar. Thanks!

**Comment by auvipy** [comment]
> Thanks! Yes, I can add the others.
> 
> @auvipy @lkollar @mayeut : if you want to confirm your PyPI username for me, I'll give you access to publish releases.

auvipy same as github

**Comment by mayeut** [comment]
> Thanks! Yes, I can add the others.
> 
> @auvipy @lkollar @mayeut : if you want to confirm your PyPI username for me, I'll give you access to publish releases.

mayeut same as github

**Comment by takluyver** [comment]
Thanks, I've added all three of you as owners on PyPI. :-)
