### ISSUE TITLE
Find a replacement for `patchelf`

### ISSUE THREAD

**Issue by lkollar** [pypa/auditwheel#174]
We rely on the `patchelf` project to repair ELF files but unfortunately it has several bugs and the fixes often take a very long time to land in a release. Releases also seem to be very infrequent.

A few example issues we have faced:
- https://github.com/NixOS/patchelf/pull/85 fixed https://github.com/pypa/auditwheel/pull/25 but the next release which shipped this fix happened only 3 years later.
- https://github.com/NixOS/patchelf/pull/171 fixes a long standing bug: https://github.com/NixOS/patchelf/issues/155. The PR has not been reviewed yet and it's unclear when/if it would get released.
- https://github.com/NixOS/patchelf/issues/94 has been open since 2016 and affects https://github.com/pypa/auditwheel/issues/29. @daa is working around this with https://github.com/pypa/auditwheel/pull/173 which is probably more productive than trying to fix this in `patchelf`.

I think it would be useful to look at potential alternatives so that we can resolve similar issues quicker. The tasks `patchelf` implements in `audithweel` today are:

- Replace `DT_NEEDED` section
- Change `SONAME`
- Update `RPATH`

If we can find a replacement which can do these, has fewer bugs and ideally a healthier release cycle, we could consider replacing `patchelf`.

One potential viable alternative I found is [LIEF](https://lief.quarkslab.com/doc/stable/index.html). I *think* it does everything we need, but I have to test it out. It's also a wrapper around a C++ project and it does not seem to ship wheels which is problematic, but we might be able to help with that.

I'm curious if anyone knows of other alternatives we could consider.

**Comment by takluyver** [comment]
Should we consider forking patchelf to fix issues that affect auditwheel? Or would the maintainers be open to us helping out? Depending on the magnitude of the problems, there's a chance that's easier than modifying auditwheel to use a different tool.

**Comment by njsmith** [comment]
During the period when we were waiting for https://github.com/NixOS/patchelf/pull/85, we did ship a custom patched build as part of manylinux image.

Another possibility to consider: contacting the patchelf maintainers and asking explicitly if they'd be up for adding some python folks as additional patchelf maintainers.

**Comment by lkollar** [comment]
I agree, we should definitely consider forking `patchelf` or helping out maintaining it. I did think of the fork option originally but somehow forgot to include it in the initial issue. I think trying to help out with the project would be best and creating a fork is a less ideal solution, so let's aim for helping out first.

I'm planning to open an issue in `patchelf` to gauge interest on taking on more maintainers and helping out in other ways to move the project forward. I'm happy to volunteer helping out. If anyone else wants to participate feel free to comment on the issue I'll link here.

**Comment by lkollar** [comment]
Created https://github.com/NixOS/patchelf/issues/174. Feel free to comment on it if you want to offer help as well.

**Comment by lkollar** [comment]
I have [this patch](https://github.com/pypa/auditwheel/pull/187) which uses LIEF instead of `patchelf` and it passes the test suite. This fixes #29 (`patchelf` bug we have a workaround for) and quite likely others as well. I should probably check if #159 gets fixed by this too.

The one caveat is that LIEF needs a modern C++ compiler so I had to build it for `manylinux1` using a CentOS 5 build of GCC 6.3 with `-static-libstdc++`. I actually ran `repair` on the resulting wheel and ended up with a correctly tagged `manylinux1` wheel, which could be uploaded to PyPI . I plan to raise this on their issue tracker and contribute this to the build process if they are interested.

Taking ownership in `patchelf` is a massive overtaking. I would still consider it if we had no alternatives, but I think in light of the success with LIEF we should definitely consider it as an alternative. 

Given that this is still a serious change and it can cause unforeseen problems, I was thinking about adding it as an extra, experimental backend to `auditwheel`. Anyone experiencing issues with the `patchelf` backend can switch to `LIEF` and if that solves the issue we can count it as a good sign. At some point we can flip the default to `LIEF` and if nobody complains we can just remove `patchelf`. The code itself is fairly simple so it should not add much maintenance work.

**Comment by figroc** [comment]
It seems that #187 hasn't merged yet. How can we try out the new patcher?

**Comment by lkollar** [comment]
LIEF 0.10.0 with proper manylinux1 support is available now so I spent some time updating the PR with the new version. However, I found a problem with RPATH patching which causes some tests to fail as the modified libraries end up containing a null NEEDED entry which triggers an assertion in `ld.so`. This might be due to a bug in LIEF. I’m planning to look into it soon.

**Comment by lkollar** [comment]
Unfortunately LIEF also has some stability issues. We cannot land #187 until https://github.com/lief-project/LIEF/issues/374 is fixed, which has been open since December. In the meantime I applied my patch to `patchelf` in the manylinux images to avoid zeroing the SONAME entry. This fixed https://github.com/pypa/auditwheel/issues/159 for `manylinux` users. We might have to follow this approach for other `patchelf` bugs as well and patch our version until a fix is merged.

I will close #187 but I plan to extract the new ELF patcher interface from it and land it separately to make the code a bit more modular. It will also make it eaiser to integrate a different patcher if we eventually find an alternative.

**Comment by domenkozar** [comment]
I think the main problem is getting regression tests for patchelf, then releases could be more frequent.

**Comment by mayeut** [comment]
@lkollar,

It would be nice to get the patcher interface from #187 even if not with lief integration.

I was thinking of creating a `patchelf` python package `auditwheel` could depend on with `patchelf` + patches prebuilt for manylinux that respects that interface. This way, it'd be easier to upgrade patchelf on manylinux images (especially with PEP600 coming) and will allow for a wider use of auditwheel without the need to build patchelf (and missing patches).

Any thoughts ?

**Comment by JanuszL** [comment]
2 cents from my side. I just experimented in our project where we are using patchelf on several MB sized libraries - https://github.com/NVIDIA/DALI/pull/1950 and LIEF is terribly slow Even printing rpath on a big library takes tens of seconds, replacing needed libraries takes several minutes as well (in case of patchelf it is just several seconds).
I think this approach could be no-go for projects with big binaries.

**Comment by lkollar** [comment]
> It would be nice to get the patcher interface from #187 even if not with lief integration.

I opened #240 for this.
> I was thinking of creating a `patchelf` python package `auditwheel` could depend on with `patchelf` + patches prebuilt for manylinux that respects that interface. This way, it'd be easier to upgrade patchelf on manylinux images (especially with PEP600 coming) and will allow for a wider use of auditwheel without the need to build patchelf (and missing patches).

I think this is a great idea. This would make it much easier to use the master branch of `patchelf` with the needed patches for any project, not only from the `manylinux` images. If you set up a repo for this I'm happy to help out with it.

**Comment by mayeut** [comment]
@lkollar,
I had time to setup a [repo](https://github.com/mayeut/auditwheel-patchelf).
It's still work-in-progress (mostly lacking documentation, not sure about the name, shall it install `patchelf` binary for real?, the setup.py is a bit complicated also...)
If you have feedback, that would be nice.

**Comment by lkollar** [comment]
Given that we can consider this a fork of `patchelf`, I agree that the package should be distributed under a different name. I think we should use the original `patchelf` binary name though as 1. it's unlikely that anyone would want both of these tools on the same system (but if one needs it, it's fairly simple to install the Python package in a different path), 2. I expect we would only apply minor fixes to the upstream package, so it should be fairly safe to use it as a substitute.

If you open issues in the repo for things which need to be done, I can assign myself and start working on them.

**Comment by matthew-brett** [comment]
But - is there any reason to keep the binary name?   Surely it would reduce the possibility for confusion if we change it to something like `py-patchelf` or `aw-patchelf`?

**Comment by lkollar** [comment]
If we installed the binary under the `auditwheel_patchelf` Python package (as it is done now), I think it's fine to leave it as `patchelf` as it won't appear on `PATH`.

**Comment by mayeut** [comment]
@lkollar,

I created issue https://github.com/mayeut/auditwheel-patchelf/issues/1 to discuss things.
In fact there are only 2 things on the list for now (check what's existing and licensing). Once they are answered, we might be able to move forward (which of course includes pooling resources with existing projects rather than having yet another solution).

Also mentioning @rmcgibbo, @jimporter as authors of packages that could do the same with update. The context is bit clearer in this issue so pinging from here for them to have some context. We can discuss furthermore in the [linked issue](https://github.com/mayeut/auditwheel-patchelf/issues/1).

**Comment by domenkozar** [comment]
Hey folks. 

First of all an apology from Nix community that we're neglecting patchelf.

I've opened https://github.com/NixOS/patchelf/issues/199 to help out here a bit.

**Comment by domenkozar** [comment]
0.11 was just released today with fixes for all the listed patches here.

**Comment by domenkozar** [comment]
With 1.3 released and a new maintainer, are you still seeing bugs?

**Comment by lkollar** [comment]
I don't recall any recent issues and I think all of the ones I mentioned in the description have been fixed. Now that `patchelf` development has picked up again I think we can close this issue. Thanks @domenkozar.

**Comment by john-science** [comment]
Sorry to be late to the party on this one, but I am on Ubuntu 20.04 and I don't seem to be able to install a newer version of `patchelf` than 0.10 and `auditwheel` is complaining that I need 0.14 or newer.

This is probably an Ubuntu problem, and not yours.  But has anyone hit this problem before?

**Comment by LecrisUT** [comment]
Recent Fedora releases are affected by https://github.com/NixOS/patchelf/issues/568. To be fair, I've tried it with `lief` and it doesn't have the same failure.

**Comment by AaronDMarasco** [comment]
I know LIEF has been mentioned as an alternative a few times. It seems they now have a [front-end wrapper available](https://lief.re/blog/2025-07-13-patchelf/) that is supposed to be able to drop-in replace `patchelf`. I was planning on looking into it later.

**Comment by LecrisUT** [comment]
> This is likely relevant for build systems as well, since (I believe) CMake, meson, and my own bfg9000 rely on patchelf for adjusting rpaths.

Not really, or at least I know for a fact that CMake does not use patchelf (except for one instance in cpack Appimage). It manipulates the elf object manually [^1].

But lief is supposed to offer a cli compatible interface, and if all goes well, distros would probably migrate to that compatibility layer. I am invastigating thia from Fedora side.

[^1]: https://github.com/Kitware/CMake/blob/ac53605f675029ef0829107ba4ec1691adc2e11c/Source/cmELF.h#L19

**Comment by jvolkman** [comment]
I wrote an [elf patcher](https://github.com/jvolkman/repairwheel/blob/main/src/repairwheel/linux/elffile.py) in Python as part of [repairwheel](https://github.com/jvolkman/repairwheel), which uses `auditwheel` under the hood but not `patchelf`. So shipping something written in pure Python as part of `auditwheel` is also an option.

**Comment by mayeut** [comment]
The release of patchelf 0.19.0 fixes the issues seen in #664.
That being said, I don't know what regressions - if any - are not seen with the tests.

Given the complexity of getting this right and the fact that maintainers of auditwheel do not necessarily have the time / knowledge to fix those kind of issues upstream, I think the less bad option would be to allow for a wider range of choices regarding ELF patchers. It comes down to users choosing the one that works well for them which is less than ideal but still offers an escape hatch should the default one be broken. At the moment, the only escape hatch is testing for various versions of patchelf.

Each of the patchers come with their bugs, there are some in lief as well, @jvolkman already reported that stripping is often broken with the pure python implementation in [repairwheel](https://github.com/jvolkman/repairwheel).
 
I wouldn't mind adding an option in the repair command to allow some kind of selection (and maybe priority) e.g. `--patcher=lief-patchelf,patchelf` would try `lief-patchelf` first then fallback to `patchelf`.

The option of getting the pure python implementation from repairwheel would most likely be linked to at least the willingness of @jvolkman to maintain it as I definitely can't commit to this (I'll  let other maintainers chime in).
