### ISSUE TITLE
auditwheel show also works on conda packages

### ISSUE THREAD

**Issue by jjhelmus** [pypa/auditwheel#18]
Not a bug report, rather a note on a nice feature.  I found that auditwheel can also be used to audit a conda package for external shared libraries.  I have not tested if any of the other sub-commands work.  Thanks for this tool, it is really helpful.

```
$ auditwheel show linux-64-tensorflow-0.7.1-py35_1.tar.bz2

linux-64-tensorflow-0.7.1-py35_1.tar.bz2 is consistent with the
following platform tag: "linux_x86_64".

The wheel references the following external versioned symbols in
system-provided shared libraries: GLIBC_2.14, CXXABI_1.3.5, GCC_3.0,
GLIBCXX_3.4.19.

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would to recompile a new wheel from
source on a system with earlier versions of these libraries, such as
CentOS 5.

The following external shared libraries are required by the wheel:
{
    "libc.so.6": "/lib64/libc-2.5.so",
    "libdl.so.2": "/lib64/libdl-2.5.so",
    "libgcc_s.so.1": "/lib64/libgcc_s-4.1.2-20080825.so.1",
    "libm.so.6": "/lib64/libm-2.5.so",
    "libpthread.so.0": "/lib64/libpthread-2.5.so",
    "libstdc++.so.6": "/usr/lib64/libstdc++.so.6.0.8",
    "libz.so.1": "/lib64/libz.so.1.2.3"
}

In order to achieve the tag platform tag "manylinux1_x86_64" the
following shared library dependencies will need to be eliminated:

libz.so.1
```

**Comment by rmcgibbo** [comment]
IIRC none of the other commands work with conda packages, but I'm glad you
got some use out of that one.

-Robert

On Fri, Mar 4, 2016 at 12:07 PM, Jonathan J. Helmus <
notifications@github.com> wrote:

> Not a bug report, rather a note on a nice feature. I found that auditwheel
> can also be used to audit a conda package for external shared libraries. I
> have not tested if any of the other sub-commands work. Thanks for this
> tool, it is really helpful.
>
> $ auditwheel show linux-64-tensorflow-0.7.1-py35_1.tar.bz2
>
> linux-64-tensorflow-0.7.1-py35_1.tar.bz2 is consistent with the
> following platform tag: "linux_x86_64".
>
> The wheel references the following external versioned symbols in
> system-provided shared libraries: GLIBC_2.14, CXXABI_1.3.5, GCC_3.0,
> GLIBCXX_3.4.19.
>
> This constrains the platform tag to "linux_x86_64". In order to
> achieve a more compatible tag, you would to recompile a new wheel from
> source on a system with earlier versions of these libraries, such as
> CentOS 5.
>
> The following external shared libraries are required by the wheel:
> {
>     "libc.so.6": "/lib64/libc-2.5.so",
>     "libdl.so.2": "/lib64/libdl-2.5.so",
>     "libgcc_s.so.1": "/lib64/libgcc_s-4.1.2-20080825.so.1",
>     "libm.so.6": "/lib64/libm-2.5.so",
>     "libpthread.so.0": "/lib64/libpthread-2.5.so",
>     "libstdc++.so.6": "/usr/lib64/libstdc++.so.6.0.8",
>     "libz.so.1": "/lib64/libz.so.1.2.3"
> }
>
> In order to achieve the tag platform tag "manylinux1_x86_64" the
> following shared library dependencies will need to be eliminated:
>
> libz.so.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pypa/auditwheel/issues/18>.
>



-- 
-Robert
