### ISSUE TITLE
Make the wheel file manylinux2010 compliant

### ISSUE THREAD

**Issue by harshad16** [pypa/auditwheel#186]
How can I make this [wheel](https://github.com/AICoE/tensorflow-wheels/releases/download/tensorflow_serving_api-r1.12-cpu-2019-08-05_191907/tensorflow_serving_api-1.12.3-py2.py3-none-any.whl) file manylinux2010 compliant? It a pure python package. 
I tried with `auditwheel repair` but didn't get any result in the `wheelhouse` directory.

**Comment by lkollar** [comment]
The manylinux platform tag is exclusively for native extensions. You should not need to apply it on pure Python packages. Why do you want to tag is as manylinux2010 compliant?

**Comment by harshad16** [comment]
It was needed due to https://www.python.org/dev/peps/pep-0571/, PyPI looking for manylinux2010 compliant packages. 
Sorry, I didn't get this part `The manylinux platform tag is exclusively for native extensions`. What do you mean by native extensions if may I ask?
Thanks, @lkollar for the response.

**Comment by takluyver** [comment]
'Native extensions' means compiled libraries, usually built from C code. They produce different binary libraries on different platforms. This is what the manylinux specifications deal with.

Wheels tagged `-none-any` are typically written in Python. The same Python code can work on all platforms, so there are no compatibility concerns. You can just use it directly.

**Comment by harshad16** [comment]
Thanks, @takluyver for the elaborate definition. 
I got a little confused as I checked the wheel with `auditwheel show` and it resulted in saying its *manylinux1* compliant. As compliance doesn't concern in this case, I will start using it.

Thanks @takluyver  and @lkollar :)

**Comment by takluyver** [comment]
I guess we could make `auditwheel show` give a more informative message if it's run on a correctly `-none-any` wheel. It's technically accurate that such a wheel is manylinux1 compliant, but that's not really helpful.
