### ISSUE TITLE
New release with manylinux2010-i686 support

### ISSUE THREAD

**Issue by veblush** [pypa/auditwheel#198]
Can we get a new release with recent PRs (#141, #194) to fix manylinux2010-i686 missing versions? Without this, i686 is not properly recognized by `auditwheel`. Also having new `auditwheel` is a prerequisite to have official `manylinux2010-i686` docker image. (https://github.com/pypa/manylinux/pull/355)

**Comment by mayeut** [comment]
done

**Comment by veblush** [comment]
Great! Thank you!
