### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by di** [pypa/auditwheel#205]
Is there anything blocking a 3.0.0 release? Any open PRs that should be included? Currently a new release would include:

### User-facing changes
- [FEATURE] manylinux2014 policy ([#192](https://github.com/pypa/auditwheel/pull/192), [#202](https://github.com/pypa/auditwheel/pull/202))
- [FEATURE] Update machine detection ([#201](https://github.com/pypa/auditwheel/pull/201))
- [FEATURE] Advertise python 3.8 support and run python 3.8 in CI ([#203](https://github.com/pypa/auditwheel/pull/203))

### Housekeeping
- Run manylinux tests using current python version ([#199](https://github.com/pypa/auditwheel/pull/199))

**Comment by mayeut** [comment]
#202 is needed for pypa/manylinux#348

**Comment by mayeut** [comment]
3.0.0.0rc1 has been released. Update in manylinux2014 images PR will follow.

**Comment by di** [comment]
It's been 1 month since we made the RC, is it time to make a proper release?

**Comment by lkollar** [comment]
I'm happy to cut a new release in the next few days. Any objections?

**Comment by lkollar** [comment]
Uploaded to https://pypi.org/project/auditwheel/3.0.0/.
