### ISSUE TITLE
ImportError: cannot import name 'open_for_csv' from 'wheel.util' (/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/wheel/util.py)

### ISSUE THREAD

**Issue by mgedmin** [pypa/auditwheel#206]
I'm not sure if this is a problem with auditwheel, or if (more likely) it's a problem with the pypa/manylinux1_x86_64 Docker image published on quay.io, but `auditwheel repair` fails for us with the following error:

```
+ auditwheel repair wheelhouse/persistent-4.5.1-cp27-cp27m-linux_x86_64.whl -w /io/wheelhouse/
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 10, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/auditwheel/main.py", line 50, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/auditwheel/main_repair.py", line 49, in execute
    from .repair import repair_wheel
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/auditwheel/repair.py", line 14, in <module>
    from .wheeltools import InWheelCtx, add_platforms
  File "/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/auditwheel/wheeltools.py", line 15, in <module>
    from wheel.util import urlsafe_b64encode, open_for_csv, native  # type: ignore
ImportError: cannot import name 'open_for_csv' from 'wheel.util' (/opt/_internal/cpython-3.7.5/lib/python3.7/site-packages/wheel/util.py)
```

Full travis build log is available at https://travis-ci.org/zopefoundation/persistent/jobs/608123705

**Comment by mgedmin** [comment]
This might be a duplicate of #102.  I see the persistent build script does `/opt/python/*/bin/pip install -U wheel` for all pythons in `/opt/python/*`.  It was my assumption that those Pythons are different from the one used by auditwheel itself (/opt/_interna/cpython-3.7.5), but that assumption could be mistaken.

**UPDATE** it was mistaken.  I've now discoverd the Dockerfile and build scripts, and it seems auditwheel is installed right into /opt/python/cp37-cp37m, which is one of those pythons where we bravely pip install -U wheel.

So this _is_ a duplicate of #102, and I'm closing it as such.

**Comment by matthew-brett** [comment]
Well - except - doesn't this mean that we need to fix the manylinux image to make sure we're installing a suitably old version of `wheel`?

**Comment by mgedmin** [comment]
The image has the right version of wheel.  Our build script was running `pip install -U pip setuptools wheel cffi` which broke things.

**Comment by matthew-brett** [comment]
Aha - thanks for correcting me.
