### ISSUE TITLE
Possible bug in symbol version lookup? "GLIBC_PRIVATE"

### ISSUE THREAD

**Issue by dralley** [pypa/auditwheel#229]
Filing this after a discussion with @njsmith on the wheel-builders mailing list.

I'm trying to build a manylinux2014-based Python wheel for the "createrepo_c" library.  It compiles properly in the docker container (and every other platform I've tried) but "auditwheel repair" always fails.

Here is the output from auditwheel repair and auditwheel show:

```
+ auditwheel show wheelhouse/createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl

createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl is consistent with the
following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libz.so.1 with versions {'ZLIB_1.2.3.5',
'ZLIB_1.2.3.3', 'ZLIB_1.2.2.3'}, liblzma.so.5 with versions
{'XZ_5.1.2alpha', 'XZ_5.0'}, libxml2.so.2 with versions
{'LIBXML2_2.4.30'}, libcrypto.so.10 with versions {'libcrypto.so.10',
'OPENSSL_1.0.1_EC'}, libc.so.6 with versions {'GLIBC_2.4',
'GLIBC_2.15', 'GLIBC_2.3.3', 'GLIBC_2.8', 'GLIBC_PRIVATE',
'GLIBC_2.7', 'GLIBC_2.14', 'GLIBC_2.3', 'GLIBC_2.2.5', 'GLIBC_2.16',
'GLIBC_2.3.2', 'GLIBC_2.17', 'GLIBC_2.3.4', 'GLIBC_2.11',
'GLIBC_2.12'}, libpthread.so.0 with versions {'GLIBC_2.3.3',
'GLIBC_2.2.5', 'GLIBC_2.3.2'}, libdl.so.2 with versions
{'GLIBC_2.2.5'}, libgssapi_krb5.so.2 with versions
{'gssapi_krb5_2_MIT'}, libidn.so.11 with versions {'LIBIDN_1.0'},
libnss3.so with versions {'NSS_3.5', 'NSS_3.21', 'NSS_3.11.2',
'NSS_3.6', 'NSS_3.13', 'NSS_3.34', 'NSS_3.22', 'NSS_3.11.1',
'NSS_3.10', 'NSS_3.12', 'NSS_3.12.5', 'NSS_3.12.6', 'NSS_3.3.1',
'NSS_3.14.3', 'NSS_3.2', 'NSS_3.14', 'NSS_3.11', 'NSS_3.8',
'NSS_3.9.3', 'NSS_3.7', 'NSS_3.4', 'NSS_3.15', 'NSS_3.9',
'NSS_3.12.1', 'NSS_3.19.1', 'NSS_3.3', 'NSS_3.9.2'}, libssl3.so with
versions {'NSS_3.2', 'NSS_3.11.4', 'NSS_3.4', 'NSS_3.14'},
libk5crypto.so.3 with versions {'k5crypto_3_MIT'}, libkrb5.so.3 with
versions {'krb5_3_MIT'}, librt.so.1 with versions {'GLIBC_2.2.5'},
libnssutil3.so with versions {'NSSUTIL_3.31', 'NSSUTIL_3.21',
'NSSUTIL_3.15', 'NSSUTIL_3.13', 'NSSUTIL_3.14', 'NSSUTIL_3.12.3',
'NSSUTIL_3.17.1', 'NSSUTIL_3.24', 'NSSUTIL_3.38', 'NSSUTIL_3.12',
'NSSUTIL_3.12.5', 'NSSUTIL_3.39'}, libm.so.6 with versions
{'GLIBC_2.2.5'}, libfreebl3.so with versions {'NSSRAWHASH_3.12.3'},
libresolv.so.2 with versions {'GLIBC_2.2.5'}, libkrb5support.so.0 with
versions {'krb5support_0_MIT'}, libkeyutils.so.1 with versions
{'KEYUTILS_0.3', 'KEYUTILS_1.0', 'KEYUTILS_1.5'}, libacl.so.1 with
versions {'ACL_1.0'}, libpopt.so.0 with versions {'LIBPOPT_0'},
libgcc_s.so.1 with versions {'GCC_3.3.1', 'GCC_3.0'}, libssl.so.10
with versions {'libssl.so.10'}, libattr.so.1 with versions
{'ATTR_1.0'}, libelf.so.1 with versions {'ELFUTILS_1.0'}

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would need to recompile a new wheel
from source on a system with earlier versions of these libraries, such
as a recent manylinux image.
+ auditwheel repair wheelhouse/createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl --plat manylinux2014_x86_64 -w /io/wheelhouse/
INFO:auditwheel.main_repair:Repairing createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl
usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot repair "wheelhouse/createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl" to "manylinux2014_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.
(.env) [vagrant@pulp3-source-fedora31 createrepo_c]$
```

I went through all of those symbols and compared them against the symbol version whitelist [here](https://github.com/pypa/auditwheel/blob/8b255b5cf09365d2fd4ab770996005df05a62b63/auditwheel/policy/policy.json)

All of the versions of GCC and Glib that are listed exist in the whitelist, except for one which is rather strange.

> libc.so.6 with versions { ..<snip>..,  'GLIBC_PRIVATE', ..<snip>..},

Is this a bug?  I don't know what ```GLIBC_PRIVATE``` is, but it doesn't match the general pattern, and I don't think this library is depending on any private glibc interfaces or anything like that.

**Comment by ehashman** [comment]
I think `GLIBC_PRIVATE` is definitely your issue. Somewhere, you have a dependency on functions that use symbols from the private GLIBC ABI. Can you use `readelf` on your wheel to try to figure out what those are and how you might have picked up the dep? It might be getting pulled in by one of your dependencies...

**Comment by dralley** [comment]
@ehashman What flags should I use?  I'm not very familiar with any of this tooling, and I don't typically work with C.  Here's what I get currently...

```
+ readelf --dyn-syms wheelhouse/createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl
readelf: wheelhouse/createrepo_c-0.15.7-cp35-cp35m-linux_x86_64.whl: Error: Not an ELF file - it has the wrong magic bytes at the start
````

**Comment by ehashman** [comment]
@dralley it would likely be helpful if you uploaded a copy of your built wheel as well as sharing the line-by-line steps you used to build it.

**Comment by dralley** [comment]
[createrepo_c.zip](https://github.com/pypa/auditwheel/files/4221208/createrepo_c.zip)

Wheels and build script in the zip file

CMD: ```docker run --rm -e PLAT=manylinux2014_x86_64 -v `pwd`:/io quay.io/pypa/manylinux2014_x86_64 /io/build_wheels.sh```

**Comment by dralley** [comment]
I thought I had linked the full code already but apparently not:  https://github.com/dralley/createrepo_c

**Comment by dralley** [comment]
The script itself is not in the source code because I want it to be done by CI eventually, just debugging the process at the moment.

I should mention that this came straight from the manylinux demo script https://github.com/pypa/python-manylinux-demo/tree/master/travis and I used the same script for 2 other packages successfully.

**Comment by lkollar** [comment]
The issue is definitely `GLIBC_PRIVATE`:

```
DEBUG:auditwheel.policy.versioned_symbols:Package requires GLIBC_PRIVATE, incompatible with policy manylinux2014_x86_64 which requires {'GLIBC_2.14', 'GLIBC_2.15', 'GLIBC_2.8', 'GLIBC_2.17', 'GLIBC_2.3.2', 'GLIBC_2.3.4', 'GLIBC_2.2', 'GLIBC_2.1.1', 'GLIBC_2.0', 'GLIBC_2.1.2', 'GLIBC_2.3.3', 'GLIBC_2.12', 'GLIBC_2.5', 'GLIBC_2.6', 'GLIBC_2.7', 'GLIBC_2.1.3', 'GLIBC_2.2.4', 'GLIBC_2.11', 'GLIBC_2.4', 'GLIBC_2.13', 'GLIBC_2.16', 'GLIBC_2.2.1', 'GLIBC_2.10', 'GLIBC_2.9', 'GLIBC_2.2.5', 'GLIBC_2.2.3', 'GLIBC_2.3', 'GLIBC_2.1', 'GLIBC_2.2.2', 'GLIBC_2.2.6'}
```

Scanning through the runtime dependencies of `_createrepo_c.so` I found a dependency on `libcrypt.so.1` which does need the `GLIBC_PRIVATE` version. This library was removed from the white list and the manylinux images have been upgraded to `libcrypt.so.2` a while back. See https://github.com/pypa/auditwheel/pull/182.

**Comment by lkollar** [comment]
Looks like project's build picks up the wrong `libcrypt.so.1`. As an experiment I created a symlink from `/usr/local/lib/libcrypt.so.2.0.0` to `/lib64/libcrypt.so.1` and after compiling the extension I was able to run `auditwheel repair` on it. 

Not sure why it is picking the wrong library though.

**Comment by dralley** [comment]
@lkollar Thank you for the help! That is strange indeed.

**Comment by dralley** [comment]
@lkollar I think this issue is a duplicate of https://github.com/pypa/manylinux/issues/411#issuecomment-568427014, which should probably be re-opened as the original issue described was not actually fixed, they just worked around it by avoiding libcurl.

But, we can't avoid libcurl.

**Comment by dralley** [comment]
I'm not sure libcurl is the actual problem, re: the other issue.  Maybe it's openssl (which libcurl links against in any case)?  But then again, I really don't know what I'm doing, or how to interpret readelf output...  Just guessing.

```
$ readelf -dV dist/createrepo_c-0.15.7-cp37-cp37m-linux_x86_64/createrepo_c/_createrepo_c.so
...
  0x0020: Version: 1  File: libcrypto.so.1.1  Cnt: 1
  0x0030:   Name: OPENSSL_1_1_0  Flags: none  Version: 6
...
```


$ rpm -qR openssl-devel                                                                                                                                                                                                                       
...
libcrypto.so.10()(64bit)                                                                                                                                                                                                                      
...

$ rpm -qR openssl-libs
...
libcrypto.so.10()(64bit)
libcrypto.so.10(OPENSSL_1.0.1_EC)(64bit)
libcrypto.so.10(libcrypto.so.10)(64bit)
...
```

Maybe ```.10``` is being interpreted as ```.1``` and using that instead of ```.2```?

**Comment by dralley** [comment]
Apologize for all the edits and comments I've made and then deleted. It's my first time dealing with any of these tools or even messing around with the concepts of symbols and linking (I know *of* them, but I'm a Python dev, not a C dev). Such is the process of learning :smile:

I'm able to confirm your results -- I'll test the packages tomorrow and verify that everything works as expected.  

Strangely, there's no reference to ```libcrypt.so.2``` in ```/lib64/``` at all, it's just in ```/usr/lib64/```.  And making a link under the name of ```libcrypt.so.2``` (instead of .1) doesn't work, it has to be .1

**Comment by njsmith** [comment]
So the issue is definitely that the build is picking up the wrong version of libcrypt. The .so.1 version is the old version that's part of libc (so we can't vendor it), but has been deprecated and isn't available on all systems anymore (so we can't assume the system will provide it, either). So there's just no way for a manylinux wheel to link to the .so.1 version.

The .so.2 version is the new standalone package, which acts like a normal shared library. So that's the version that you need to use.

There are two ways you might be picking up the wrong version:

- Option 1: you're building some C code, and the build system (autoconf or whatever) somehow finds the wrong version. This isn't *supposed* to happen; the manylinux images are supposed to be set up in a way that prevents that. But it's possible that there's some bug somewhere and it's not working right.

- Option 2: you're using pre-built libraries provided by the distribution, and those have been built to use the distro-provided libcrypt.so.1.

I think the second option is more likely. For example, maybe when you dnf install libcurl, you get a library that uses libcrypt.so.1. If that's what's going on, then what it means is that you can't use the distro-provided libcurl; instead you need to download the libcurl source and build it yourself, making sure that it uses libcrypt.so.2.

(Libcurl is just an example here. Replace with "any libraries that use libcrypt.so.1.)

**Comment by myselfhimself** [comment]
> @lkollar I think this issue is a duplicate of [pypa/manylinux#411 (comment)](https://github.com/pypa/manylinux/issues/411#issuecomment-568427014)? Or they are at least possibly talking about the same issue.
> 
> They claim they avoided the issue by avoiding libcurl, which we can't do.

Hello... I filed that very #411 issue, and in the end in our case we fall back on using the platform's curl executable when libcurl is not linked... I am following the present issue, in case some solution finally were landed, but have no more clue on a workaround sorry.

**Comment by dralley** [comment]
So the packages built with the hack @lkollar described do not work, they fail at import time

```
(.env) [vagrant@pulp3-source-fedora31 createrepo_c]$ pip install ../../createrepo_c-0.15.7-cp37-cp37m-manylinux2014_x86_64.whl
Processing /home/vagrant/devel/createrepo_c-0.15.7-cp37-cp37m-manylinux2014_x86_64.whl
Installing collected packages: createrepo-c
Successfully installed createrepo-c-0.15.7
(.env) [vagrant@pulp3-source-fedora31 createrepo_c]$ python3
Python 3.7.4 (default, Aug 12 2019, 14:45:07) 
[GCC 9.1.1 20190605 (Red Hat 9.1.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import createrepo_c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.env/lib64/python3.7/site-packages/createrepo_c/__init__.py", line 8, in <module>
    from . import _createrepo_c
ImportError: /home/vagrant/.env/lib64/python3.7/site-packages/createrepo_c/.libs/libcrypto-957ef781.so.1.0.2k: version `libcrypto.so.10' not found (required by /home/vagrant/.env/lib64/python3.7/site-packages/createrepo_c/_createrepo_c.so)
```

**Comment by dralley** [comment]
I believe @njsmith is right, and it is option 2.  ```libcurl``` links against ```libcrypt.so.1``` inside the environment.  That is why I get different results for ```ldd``` on my Fedora host (```libcrypt.so.2```), and why ```readelf``` doesn't mention ```libcrypt``` at all -- because it's not a direct dependency.

This is an environmental problem so I will close this issue in favor of @myselfhimself 's issue.
https://github.com/pypa/manylinux/issues/411#issuecomment-590483846
