### ISSUE TITLE
Can 'auditwheel repair' be ported in any form to MacOS?

### ISSUE THREAD

**Issue by bsolomon1124** [pypa/auditwheel#234]
Auditwheel enables me to bundle external shared libraries into `manylinux` wheels.  My understanding of what this means is that there is no need for a `dlopen()` call at runtime.

It looks like auditwheel only works on Linux, however.  Is there any way, even if more tedious, to do the same on MacOS?  What would that look like, at a high level?

In this case, I am trying to distribute a C++ extension module that depends on [Protobuf](https://github.com/protocolbuffers/protobuf/tree/master/src).  Even if I can successfully build a MacOS wheel, the user will still need a `brew install protobuf`, otherwise they'll get an error like:

```
ImportError: dlopen(site-packages/xyz.cpython-38-darwin.so, 2): Library not loaded
/usr/local/opt/protobuf/lib/libprotobuf.22.dylib
```

This is not the case with Linux (where auditwheel does exactly what it says it does!).

**Comment by jamadden** [comment]
You may want the [delocate utility](https://github.com/matthew-brett/delocate), described [in the MacPython wiki](https://github.com/MacPython/wiki/wiki/Spinning-wheels#so---nothing-can-go-wrong-with-macos-binary-wheels).

**Comment by bsolomon1124** [comment]
Thanks @jamadden , that seems to be exactly what I was going for. I'll give it a try.
