### ISSUE TITLE
How to update policy.json for a PEP 600 perennial manylinux spec

### ISSUE THREAD

**Issue by mattip** [pypa/auditwheel#239]
The current specs in [policy.json](https://github.com/pypa/auditwheel/blob/8b255b5cf09365d2fd4ab770996005df05a62b63/auditwheel/policy/policy.json) relate to `GLIBC`, `CXXABI`, `GLIBCXX`, and `GCC` while [PEP 600](https://www.python.org/dev/peps/pep-0600/#package-installers) specifies only `GLIBC`. In a perennial manylinux world, what should become of the other values? What should the `lib_whitelist` be?

**Comment by njsmith** [comment]
In the perennial manylinux world, all the symbol versions and whitelist and so on stay the same, just now they can be defined and updated directly based on what works (by examining CentOS releases, responding to bug reports, etc.), without having to go through a PEP along the way.

**Comment by mattip** [comment]
Thanks.
