### ISSUE TITLE
rename vendored libraries

### ISSUE THREAD

**Issue by njsmith** [pypa/auditwheel#24]
as per here:
https://mail.python.org/pipermail/wheel-builders/2016-March/000082.html

**Comment by njsmith** [comment]
On further investigation, it looks like there are actually five required steps to properly vendor an ELF library:

1) Move vendored library into `.libs`
2) Run `patchelf --set-rpath path/to/.libs OBJ` on all the objects that link to the vendored library
3) Rename the library, e.g. from `libfoo.so.1` to `libfoo-<unique>.so.1`
4) Run `patchelf --replace-needed libfoo.so.1 libfoo-<unique>.so.1 OBJ` on all the objects that link to the vendored library, so that they look for the new name.
5) Crucial, but not at all obvious: Run `patchelf --set-soname libfoo-<unique>.so.1 .libs/libfoo-<unique>.so.1` so that the renamed library knows what its new name is. (The DT_SONAME attribute is what's checked when deciding whether to short-circuit later library lookups, so this is crucial -- if we didn't change this, then when someone else came along looking for `libfoo.so.1` then it would think that the already-loaded `libfoo-<unique>.so.1` satisfied that.)

**Comment by njsmith** [comment]
Also, NB that `--replace-needed` and `--set-soname` are new features in `patchelf` 0.9, which is not yet shipped by e.g. Debian.

**Comment by njsmith** [comment]
@rmcgibbo @ogrisel: looks like this is now the one big blocker for mass uploading of manylinux wheels now... any chance one of you has a chance to look at it?

**Comment by rmcgibbo** [comment]
Yeah, I think I can handle it tonight or tomorrow day.

**Comment by matthew-brett** [comment]
Great - that would be a big help.
