### ISSUE TITLE
Do not place OpenGL libraries into wheels on manylinux*

### ISSUE THREAD

**Issue by mathstuf** [pypa/auditwheel#241]
These libraries really need to come from the end machine, not the wheel. They don't work without a backing video driver and may not work if the package was built on a machine with a different driver than the end machine (e.g., mixing an nvidia driver `libOpenGL` with a Mesa DRI `libOpenGL`). The backing DRI libraries aren't packaged anyways, so they're of limited utility either way.

**Comment by mattip** [comment]
I see that `libGL` is already part of the [allowlist policies](https://github.com/pypa/auditwheel/blob/main/src/auditwheel/policy/manylinux-policy.json#L66). Is there also a `libOpenGL` that should be allowlist-ed?

**Comment by mathstuf** [comment]
Note that the PR that closed this only adds an `--exclude` flag. Is there some way to have PyPI add this flag when verifying uploads? Or does this need a formal PEP?
