### ISSUE TITLE
Replace `unzip` usage with Python's `zipfile`

### ISSUE THREAD

**Issue by FFY00** [pypa/auditwheel#258]
Would it be possible to replace the `unzip` usage with Python's `zipfile`? I see no reason to have an external dependency such as this.

https://github.com/pypa/auditwheel/blob/8fc14ac8943fd1cd8f6b350ce6f0432f749ef17c/auditwheel/tools.py#L43

**Comment by lkollar** [comment]
According to the comment [above](https://github.com/pypa/auditwheel/blob/8fc14ac8943fd1cd8f6b350ce6f0432f749ef17c/auditwheel/tools.py#L41-L42), `unzip` is used to work around an issue where permissions are not correctly preserved. If we can ensure the behaviour is preserved, we can replace it with `ZipFile`, but it won't be a trivial change probably.

Alternatively, once https://github.com/pypa/wheel/pull/357 is landed and `wheel` will have a public API, we might be able to use that and drop the code dealing with ZIP files.

**Comment by FFY00** [comment]
Sure, although you can still access the permissions in `zipfile.ZipInfo` IIRC. You can use `infolist` to set the permissions after the extraction, should be a pretty straight forward patch.

The reason I am asking this is because `unzip` is a custom external program. It is not part of any operating system. Some Linux distributions might include it by default, but definitely not all, it might also be missing.
