### ISSUE TITLE
Not complying to PEP 427 (`policy.json` and `policy-schema.json`) & egg installs are broken

### ISSUE THREAD

**Issue by FFY00** [pypa/auditwheel#259]
PEP 427 says that any file that is not normally installed to site-packages, which is the case of `policy.json` and `policy-schema.json`, should be installed to `distribution-version.data` ([here](https://www.python.org/dev/peps/pep-0427/#the-data-directory)).

Currently, the build is relying on custom undocumented behavior from the build backend. Slightly related, installation via eggs is broken, these files don't get installed. Even though egg installs are deprecated, they are still in use in some places such as Linux distributions, which currently don't have an alternative workflow available (that is being worked on).

**Comment by FFY00** [comment]
Solution: https://python-packaging.readthedocs.io/en/latest/non-code-files.html

**Comment by chrisantonellis** [comment]
Is this ticket still valid? Through testing am seeing `policy.json` and `policy-schema.json` installed to site-packages by default. Can you provide more context on the acceptance criteria? Thanks!!

**Comment by FFY00** [comment]
Relating to PEP 427 compliance, it's kind of subjective, one could argue the files are fine there. Though the egg issue is still very valid, and I think the files would probably be better in the package data directory. `importlib.resources` has been in the standard library for a little while, so it's an inexpensive thing too.

**Comment by lkollar** [comment]
> Solution: https://python-packaging.readthedocs.io/en/latest/non-code-files.html

Given that auditwheel now follows the exact process described here, I'm closing this.
