### ISSUE TITLE
Tests are failing on ppc64le

### ISSUE THREAD

**Issue by mayeut** [pypa/auditwheel#292]
`ppc64le` are failing on travis-ci due to an unknown infra change on their end.

**Comment by mayeut** [comment]
xref Travis CI post https://travis-ci.community/t/running-out-of-disk-space-quota-when-using-docker-on-ppc64le/11634

**Comment by lkollar** [comment]
Closing this since #293 allows failures on ppc64le. @mayeut if you think there is more work here, feel free to reopen it.
