### ISSUE TITLE
Add manylinux_2_27 policy

### ISSUE THREAD

**Issue by auscompgeek** [pypa/auditwheel#299]
Hey team!

We at @robotpy build wheels on Ubuntu 18.04 (as our upstream targets 18.04). We've been manually tagging our wheels as `manylinux_2_27` as we wanted to get our wheels on PyPI quickly early this year. It'd be awesome if we could use auditwheel instead to check that our wheels are actually compliant.

**Comment by mayeut** [comment]
Hello @auscompgeek,

I created #300 to add the `manylinux_2_27` policy. I'm not sure how we can test this policy in CI for now. Could you please have a look to check wether or not you're seeing issues on wheels from @robotpy (unless others are doing the same thing as you are, that would be roughly 15 packages ?)

**Comment by auscompgeek** [comment]
Awesome, thanks! Looks like auditwheel is satisfied our existing wheels (grabbed from downloading `robotpy[all]`) is consistent with manylinux_2_27, with the exception of our robotpy-halsim-* packages which apparently have an existing unrelated problem we've overlooked.
