### ISSUE TITLE
mentioning PEP 600 in the `README.rst`

### ISSUE THREAD

**Issue by johnyf** [pypa/auditwheel#302]
Support for [PEP 600](https://www.python.org/dev/peps/pep-0600/) appears to have started being introduced in `auditwheel == 3.3.0` (based on the file [`CHANGELOG.md`](https://github.com/pypa/auditwheel/blob/242dcfdbd94fa59436482f0c7ef38db0946df6a2/CHANGELOG.md#user-facing-changes-1)) (#246 and #239, too, are relevant). Some recent changes that are relevant are commits 3ac70ffba72b86939ea06efcce67c7c0cce16993, 70e167d39e742ba6c33879b8d3de42bebba6e369, and 7d4090b6281ba5e538f619d1c04ddee409a7a8ef. Based on the files:
- https://github.com/pypa/auditwheel/blob/242dcfdbd94fa59436482f0c7ef38db0946df6a2/auditwheel/policy/policy.json
- https://github.com/pypa/auditwheel/blob/242dcfdbd94fa59436482f0c7ef38db0946df6a2/auditwheel/main_repair.py#L18-L22
the PEP 600 specification appears to be supported.

As of 242dcfdbd94fa59436482f0c7ef38db0946df6a2, PEP 600 is not mentioned in the file [`README.md`](https://github.com/pypa/auditwheel/blob/242dcfdbd94fa59436482f0c7ef38db0946df6a2/README.rst).

I do not know whether this is intentional, so I am noting it.

**Comment by auvipy** [comment]
you can send PR to update readme

**Comment by johnyf** [comment]
Thank you for suggesting opening a pull request, I just did.

**Comment by johnyf** [comment]
Addressed in dc250fd6ac34618513bb13c1ec163cc4f18ab523.
