### ISSUE TITLE
Error "wheel has to be platlib compliant in order to be repaired by auditwheel"

### ISSUE THREAD

**Issue by tcuongd** [pypa/auditwheel#333]
Hi! I'm trying to use `cibuildwheels` + Github Actions for the Prophet package but I'm struggling to get the Repair step of the build working on Linux (i.e. the wheel finishes building, but can't be repaired by auditwheel). I'm keen to understand more about the error

```
RuntimeError: Invalid binary wheel, found the following shared library/libraries in purelib folder:
  	prophet_model.bin
  	diagnose
  	print
  	stanc
  	stansummary
  	diagnose.o
  	print.o
  	stansummary.o
  	bernoulli
  	main.o
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```

I'm not quite sure what "platlib compliant" means. I found a similar discussion here: https://github.com/google/or-tools/issues/616#issuecomment-371480314 and tried to apply the suggested fix but ran into the same error. Would really appreciate any help on this one!

[Here](https://github.com/facebook/prophet/runs/3452729484?check_suite_focus=true) is the CI run in question, if that helps.

**Comment by mayeut** [comment]
There's a similar discussion in https://stackoverflow.com/questions/45150304/how-to-force-a-python-wheel-to-be-platform-specific-when-building-it
Maybe this can help.

**Comment by tcuongd** [comment]
Thanks Matthieu! So I tried using:

```py
class BinaryDistribution(Distribution):
    """Distribution which always forces a binary package with platform name"""
    def has_ext_modules(self):
        return True

    def is_pure(self):
        return False
```

in setup.py, but the error is the same :( I'm just using https://github.com/pypa/build to build the wheel, not sure if that has something to do with it.

**Comment by mayeut** [comment]
As mentioned in pypa/packaging-problems#542, it's more a `setuptools` usage issue so I'll close this one as there's not much that can be done in auditwheel.
