### ISSUE TITLE
Only bundle some select libraires

### ISSUE THREAD

**Issue by FFY00** [pypa/auditwheel#339]
Hello, I have a use-case where I only want auditwheel to bundle certain libraries. i.e. I only want auditwheel to bundle `libfoo1.so` and `libfoo2.so`. Would it be possible to allow doing this?

From https://github.com/pypa/auditwheel/issues/82#issuecomment-919086441:
> In my use-case in specific, I am writing a backend that packages Meson projects into Python wheels. I use auditwheel to both include system dependencies, so that the wheels can be distributed on PyPI, but also include Meson built artifacts in the wheels.
> The issue is that I want to make the inclusion of system libraries optional, as that is undesirable for many distro packagers and/or users. For this, I would need to run the wheel repair process with a custom policy, to only include the Meson artifacts.

**Comment by FFY00** [comment]
I just noticed #310's `--include` would solve this.

**Comment by lkollar** [comment]
I think you could achieve this with the `--exclude` option now. If you think an `--include` flag would be still useful, feel free to reopen this.
