### ISSUE TITLE
Rename the default branch from `master` to `main`

### ISSUE THREAD

**Issue by DiddiLeija** [pypa/auditwheel#341]
Hi folks!

I can see that many PyPA repos changed its default branch to `main`. Can we do the same here?

**Comment by DiddiLeija** [comment]
Can we do this?

**Comment by mayeut** [comment]
`master` is now named `main`

If you have a local clone, you can update it by running the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by DiddiLeija** [comment]
Thanks @mayeut!
