### ISSUE TITLE
Is wheel built on CentOS 8 (glibc 2.28) supported? 

### ISSUE THREAD

**Issue by wenleix** [pypa/auditwheel#351]
Hi, 

I am building my my wheel on CentOS 8, the glibc version is 2.28. But looks like auditwheel's `--plat` parameter only supports up to `manylinux_2_27_x86_64`: 

```
auditwheel repair: error: argument --plat: invalid choice: 'manylinux_2_28_x86_64' (choose from 'linux_x86_64', 'manylinux_2_5_x86_64', 'manylinux_2_12_x86_64', 'manylinux_2_17_x86_64', 'manylinux_2_24_x86_64', 'manylinux_2_27_x86_64', 'manylinux1_x86_64', 'manylinux2010_x86_64', 'manylinux2014_x86_64')
```

However, `auditwheel show` suggests me to use platform tag `manylinux_2_27_x86_64`, and indeed it repair the wheel with tag `manylinux_2_27_x86_64`: 

```
The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_3.0'}, libdl.so.2 with versions {'GLIBC_2.2.5'}, libpthread.so.0
with versions {'GLIBC_2.12', 'GLIBC_2.2.5', 'GLIBC_2.3.2'}, libm.so.6
with versions {'GLIBC_2.2.5'}, libc.so.6 with versions {'GLIBC_2.17',
'GLIBC_2.3', 'GLIBC_2.2.5', 'GLIBC_2.7', 'GLIBC_2.16', 'GLIBC_2.25',
'GLIBC_2.3.4', 'GLIBC_2.12', 'GLIBC_2.14', 'GLIBC_2.15', 'GLIBC_2.9',
'GLIBC_2.4', 'GLIBC_2.3.2', 'GLIBC_2.10', 'GLIBC_2.8'}, libstdc++.so.6
with versions {'GLIBCXX_3.4.5', 'CXXABI_1.3.5', 'GLIBCXX_3.4',
'GLIBCXX_3.4.20', 'CXXABI_1.3.11', 'GLIBCXX_3.4.11', 'CXXABI_1.3.3',
'CXXABI_1.3.9', 'GLIBCXX_3.4.14', 'CXXABI_1.3.7', 'GLIBCXX_3.4.22',
'GLIBCXX_3.4.21', 'GLIBCXX_3.4.18', 'CXXABI_1.3.2', 'CXXABI_1.3.8',
'GLIBCXX_3.4.9', 'GLIBCXX_3.4.15', 'GLIBCXX_3.4.2', 'CXXABI_1.3',
'GLIBCXX_3.4.19'}

This constrains the platform tag to "manylinux_2_27_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```

I am wondering:

1. Will auditwheel supports platform `manylinux_2_28_x86_64`? (e.g. CentOS 8)
2. For my wheel, although it's built with GLIBC 2.28 , if auditwheel suggests to use platform tag `manylinux_2_27_x86_64`, can I still publish that? 

Thank you so much!

**Comment by mayeut** [comment]
Hi @wenleix,

sorry for the late reply.

> 1. Will auditwheel supports platform `manylinux_2_28_x86_64` ? (e.g. CentOS 8)

It will, eventually.

> 2. For my wheel, although it's built with GLIBC 2.28 , if auditwheel suggests to use platform tag `manylinux_2_27_x86_64`, can I still publish that?

Yes, you can publish this one. It means auditwheel did not detect anything that would require anything more than `manylinux_2_27_x86_64` in your wheel. It will install on any linux distro with glibc 2.27+ (with pip>=20.3)
