### ISSUE TITLE
Can I audit a py39 whl file using an auditwheel package under python3.7?

### ISSUE THREAD

**Issue by dongrixinyu** [pypa/auditwheel#379]
- Can I audit a py39 whl file using an auditwheel package under python3.7?
- It means difference between auditwheel python version and the whl python version. That does not make an influence on the final result, right?
- Appreciate your reply! Thanks!

**Comment by mayeut** [comment]
> Can I audit a py39 whl file using an auditwheel package under python3.7?

Yes you can. You can still audit python 2.7/3.4/3.5 while auditwheel itself requires running 3.6+.

> That does not make an influence on the final result, right?

No it doesn't.
