### ISSUE TITLE
Add support for Jammy (glibc 2.35)

### ISSUE THREAD

**Issue by mwoehlke-kitware** [pypa/auditwheel#388]
As of writing, the latest Ubuntu LTS is Jammy, shipping with glibc 2.35, which is not supported yet. This also seems to be an obvious candidate for Python 3.10 support (Focal does not have 3.10). Is `manylinux_2_35_x86_64` on the roadmap to be added soon? Is there anything we can do to help the process?

**Comment by mayeut** [comment]
> Is manylinux_2_35_x86_64 on the roadmap to be added soon?

There are still some rolling distros on glibc 2.35 with symbols lower than the ones provided by ubuntu 22.04
It's thus best to wait a bit before defining the policy.

> This also seems to be an obvious candidate for Python 3.10 support

Well, it depends on what you mean by obvious, for me the obvious candidate is the manylinux2014 image but that does not mean it's the obvious for someone else (to each one is constrains and choices).

>  Focal does not have 3.10

Well, again, it does not provide it as a default but there's [the dead snakes  ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) and also, most of CI providers will provide you with python 3.10 on ubuntu 20.04.

**Comment by johnnynunez** [comment]
where is it? https://quay.io/search?q=manylinux_2_35_x86_64
