### ISSUE TITLE
Do not white list libnsl.so.1

### ISSUE THREAD

**Issue by cquike** [pypa/auditwheel#406]
I have created a manylinux2014 wheel which has a library that depends on libnsl.so.1. It seems that this library is whitelisted by auditwheel and is expected to be part of the system.
However libnsl.so.1 is not provided by by default by newer systems. For instance, the wheel fails to work in Rocky Linux 8, which has  libnsl.so.2. libnsl _is_ also provided by Rocky Linux 8 (and newer Fedoras), but it is not part of the system default installation and needs to be installed on purpose by the user.
Would it be possible to not whitelist libnsl.so.1 anymore so that wheels that depend on it can be easily distributed?
Thanks!

**Comment by mayeut** [comment]
`libnsl.so.1` can't be grafted (depends on internal GLIBC symbols) so if it's not whitelisted, it won't succeed to be grafted and will leave you with an unrepairable wheel which is probably worse than the current status.

**Comment by cquike** [comment]
Thanks for the explanation. So if I understand correctly the only way to install those wheels is basically to install libnsl.so.1 in the target system, right? That kind of defeats the purpose of the manylinux idea of providing easy installation for the final user, but I guess that there is no easy solution here.

**Comment by mayeut** [comment]
> That kind of defeats the purpose of the manylinux idea of providing easy installation for the final user, but I guess that there is no easy solution here.

Well, the future holds what it holds so the definition made years ago based on some knowledge at that time are not always still valid these days (mostly is still valid, the same issue arises with libcrypt.so.1 but there was an alternative implementation that could be grafted. If you do know of one for libnsl.so.1, please do share).

> So if I understand correctly the only way to install those wheels is basically to install libnsl.so.1 in the target system, right?

Yes, but maybe you can do something about it.

If `libnsl.so.1` is a direct dependency, you should probably drop it ?

If it's an indirect dependency,
You're either grafting it from a system dependency: maybe providing wheels for a newer manylinux policy (by building e.g. on manylinux_2_28) will drop this dependency. If you want to support older glibc systems, you can build twice, newer systems should get newer wheels without the dependency, older systems will get the older wheels with the dependency but that should not matter on older systems.

A dependency you built yourself: maybe you can disable libnsl usage ?

**Comment by cquike** [comment]
Thank you very much for sharing those ideas!
It is an indirect dependency . Our direct dependency is libxerces.
Most likely the idea of providing wheels for both manylinux 2014 and manylinux 2.28 is indeed the way to go.
Thanks again!
