### ISSUE TITLE
armv7 QNAP Docker:  wheels with SEGFAULT

### ISSUE THREAD

**Issue by magicse** [pypa/auditwheel#414]
@Wetzel402 @Gerigot
Without auditwheel all packages work well.  But after repairing with auditwheel I get SEGFAULT
Also the same problem with other packages (with shared libs libstdc++ and libgcc_s) in this docker image.
Here is my test https://github.com/home-assistant/core/issues/86589#issuecomment-1455094527
And this link https://github.com/home-assistant/core/issues/86589 to the start of the discussion thread
As a result of the experiments, it turned out that the problem is auditwheel + patсhelf

The strange thing is that in Qemu emulation such a package works, but not on real ARMv7
General problem that wheel repaired in Qemu Docker image work in Qemu but didnt work in the same image Docker on real ARMv7, and without wheelaudit built packages work well.  
GDB show that problem in  /usr/local/lib/python3.10/site-packages/*.libs/libstdc++-ad7c573d.so.6.0.29 .libs/libgcc_s-8c7760c8.so.1

**Comment by mayeut** [comment]
This is most likely a bug in patchelf.
You should be able to work around this by statically linking libstdc++ and libgcc_s when building the cchardet wheel.

**Comment by magicse** [comment]
> You should be able to work around this by statically linking libstdc++ and libgcc_s when building the cchardet wheel.
I'd be happy to get around but I don't make wheels for Home Assistant, they make wheels with those libraries included. It seems to me that I already got everyone there ... with this problem.

> Edit: the fact that it works with qemu seems weird though.
And yes it very strange.
