### ISSUE TITLE
libpython3.x is skipped but libpython3.xx is included

### ISSUE THREAD

**Issue by sergeyasad** [pypa/auditwheel#418]
howdy,

i noticed when running auditwheel repair on a wheel with dependency on libpython3.8.so or libpython3.9.so, they are not added to the wheel libs directory, but libpython3.10.so and libpython3.11.so are added. I'm not very familiar with the project, but i suspect [the regex detecting libpython](https://github.com/pypa/auditwheel/blob/63c30761e6857491af50fbb1922ecfd4c034ef76/src/auditwheel/policy/external_references.py#L11) could be the culprit

**Comment by mayeut** [comment]
I think you're right about the culprit here.
This is most likely an issue with the regex.
A PR with a fix and a test are welcome.
