### ISSUE TITLE
Using repair --exclude can't transfer the linux_x86_64 to manylinux_x_y

### ISSUE THREAD

**Issue by LIONEFAN** [pypa/auditwheel#422]
Due to my wheel links to `_pywrap_tensorflow_internal.so` in Tensorflow package. So I have to use --exclude to prevent to include this .so in my wheel(Because that will result to my manylinux wheel too big). And it tell me have successfully convert the  tag from linux_x86_64 to manylinux2014_x86_64/manylinux_2_17_x86_64

But when I use the commond `auditwheel show my_manylinux_wheel` 
It shows my wheel tag is still `linux_x86_64`

Is it a normal situation that I should ignore? Or is it a bug that about the `auditwheel show`?

**Comment by mayeut** [comment]
For now I'd say it's a normal situation you can ignore.
`auditwheel show` has to learn about `--exclude` in order to report the correct tag.

**Comment by LIONEFAN** [comment]
> For now I'd say it's a normal situation you can ignore. `auditwheel show` has to learn about `--exclude` in order to report the correct tag.

OK, I will ignore this situation. Thank you!
