### ISSUE TITLE
auditwheel library vendoring doesn't handle executable binaries correctly

### ISSUE THREAD

**Issue by njsmith** [pypa/auditwheel#425]
Here's a broken manylinux wheel generated by auditwheel: https://files.pythonhosted.org/packages/58/44/997cf22b98d38a297a7fba6b950d88203bc0750511c06a4f5064c7039b5f/perpetuo-0.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

The issue is:

This wheel contains an executable (not package!) named `perpetuo`, that gets installed into the python environment's `bin/` dir (or `Scripts/` on Windows, but this is a Linux problem). That binary depends on some `libunwind-*.so` shared objects.

Auditwheel correctly detects the dependency, and attempts to vendor `libunwind-*.so` into the wheel. But! It assumes that shared objects are always extension modules, not executables, so it vendors `libunwind-*.so` into the library directory, and gives `perpetuo` an RPATH pointing from where `perpetuo` is located in the wheel, to where `libunwind-*.so` are located in the wheel:

```
$ readelf -a bin/perpetuo  | grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [$ORIGIN/../../perpetuo.libs]
```

A digression on [how wheel files are laid out](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format):

- Wheels are just zip files
- By default, a path `foo/bar/...` in the zip file gets placed at `site-packages/foo/bar/...`.
- But, any zip path that starts `packagename-version.data/scripts/foo` instead gets placed in `bin/foo`

So auditwheel's RPATH here is trying to point from `perpetuo-0.3.0.data/scripts/perpetuo` to `perpetuo.libs/`, but this doesn't work, because when the wheel is unpacked those two files end up moved to different places.

I think the only fully general solution here is to detect when a binary is in the `packagename-version.data/scripts` directory, and if so then vendor all of its dependencies into something like `packagename-version.data/scripts/packagename.libs` and point RPATH at that?

**Comment by mayeut** [comment]
duplicates #340
