### ISSUE TITLE
install auditwheel': The system cannot find the file specified

### ISSUE THREAD

**Issue by DMTarmey** [pypa/auditwheel#428]
PS C:\Users\Dell User\Auto-GPT\.devcontainer> & "c:/Users/Dell User/Auto-GPT/.devcontainer/env/Scripts/Activate.ps1"
(env) PS C:\Users\Dell User\Auto-GPT\.devcontainer> pip3 install auditwheel
Fatal error in launcher: Unable to create process using '"C:\Users\Dell User\Auto-GPT\env\Scripts\python.exe"  "C:\Users\Dell User\Auto-GPT\.devcontainer\env\Scripts\pip3.exe" install auditwheel': The system cannot find the file specified.

Error log 

2023-05-10 10:10:05,503 ERROR logs:_log:143 Error: The following AI output couldn't be converted to a JSON:
 {
    "thoughts": {
        "text": "After reviewing the content, I have found that it is accurate and informative. I should now use the 'get_hyperlinks' command to gather relevant hyperlinks that can be used to support the information presented in the article.",
        "reasoning": "Gathering relevant hyperlinks will help to support the information presented in the article and increase its credibility. Using the 'get_hyperlinks' command will help me to quickly and efficiently gather these hyperlinks.",
        "plan": "- Use the 'get_hyperlinks' command to gather relevant hyperlinks\n- Review the hyperlinks to ensure that they are reliable and trustworthy\n- Incorporate the hyperlinks into the article to support the information presented",
        "criticism": "I should be careful to ensure that all hyperlinks are reliable and trustworthy, and that they support the information presented in the article. I should also strive to use language that is clear and concise, and avoid using jargon or technical terms that may be difficult for readers to understand.",
        "speak": "To gather relevant hyperlinks that can be used to support the information presented in the article, I suggest using the 'get_hyperlinks' command."
    },
    "command": {
        "name": "get_hyperlinks",
        "args": {
            "url": "https://en.wikipedia.org/wiki/GPT-3",
        }
    }
}
2023-05-10 10:47:00,463 ERROR logs:_log:143 The JSON object is invalid. 
2023-05-10 12:05:50,429 ERROR logs:_log:143 Error:

**Comment by lkollar** [comment]
This is not an auditwheel issue. There seems to be something wrong with the pip invocation, but this wouldn't work on Windows anyway as auditwheel is Linux-only.
