### ISSUE TITLE
Addtag always tries to add linux_x86_64 tag

### ISSUE THREAD

**Issue by lkollar** [pypa/auditwheel#444]
> This might be a bug in `addtag`, but I'm not even sure what this subcommand is useful for. It seems to try to assign the minimum compatible tag in the file name, but from my limited testing it always ends up with the `linux_x86_64` tag, which isn't useful. So if you pass a wheel which only has a `linux_x86_64` tag, it does nothing, and for wheels which have manylinux tags it also adds `linux_x86_64`, which isn't very useful either. I wonder if this is a regression, as there aren't any real tests for this functionality...

_Originally posted by @lkollar in https://github.com/pypa/auditwheel/issues/439#issuecomment-1705711191_

**Comment by mayeut** [comment]
I wonder if we should simply remove this command in auditwheel 6.0.0 ?
As you mentioned, I don't know how useful this is...

**Comment by lkollar** [comment]
I'd in favour of removing it. It doesn't seem useful in its current form at all.
