### ISSUE TITLE
reduce manylinux package name length

### ISSUE THREAD

**Issue by MrBitBucket** [pypa/auditwheel#465]
I raised an issue here https://discuss.python.org/t/limits-on-pypi-download-name-length/37700/3 concerning a long manylinux package name. 

There is a suggestion from Brett Cannon that the package name can be shortened considerably because packaging.tags will be used to generate the relevant information.

I raised this as a cibuildwheel issue 1654, but they say auditwheel decides this, however, I suppose that there are facts about the pypi/pip interaction that will make this more or less possible.

**Comment by mayeut** [comment]
You can shorten the name by using `--only-plat` or modifying the default `--plat`
The name `rl_accel-0.9.0-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl` mentioned in the discussion would become:
- with `--only-plat`: `rl_accel-0.9.0-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`
- with `--plat manylinux1_x86_64`: `rl_accel-0.9.0-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl`

This option to choose depends on what you want to support. You can also mix the 2 options:
- with `--plat manylinux2010_x86_64 --only-plat`: `rl_accel-0.9.0-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl`
