### ISSUE TITLE
Full example; from building the initial wheel to repairing it using auditwheel

### ISSUE THREAD

**Issue by mtrienis** [pypa/auditwheel#60]
I was hoping to get a full blown example using the `setup.py` that built 

```cffi-1.5.0-cp35-cp35m-linux_x86_64.whl```

I'm not sure how to include the `.so` files as dependencies when building the initial wheel i.e: 
```
{
    "libc.so.6": "/lib64/libc-2.5.so",
    "libffi.so.5": "/usr/lib64/libffi.so.5.0.6",
    "libpthread.so.0": "/lib64/libpthread-2.5.so"
}
```

Thanks, Mike.

**Comment by njsmith** [comment]
I'm not sure I understand the question -- I think that wheel was just built by downloading the cffi source code and running `python setup.py bdist_wheel`?

Possibly useful resources:

* An example project building manylinux wheels: https://github.com/pypa/python-manylinux-demo

* How to build extension modules with distutils (and specifically the `libraries=` argument to `Extension`, which gives libraries that you want to link against): https://docs.python.org/3/extending/building.html#building-c-and-c-extensions-with-distutils

**Comment by mtrienis** [comment]
Thanks for your reply, I think you are right, my question is more related to the resource you mentioned here: 

- https://docs.python.org/3/extending/building.html#building-c-and-c-extensions-with-distutils

I'll close the ticket.
