### ISSUE TITLE
Auditwheel 1.6 breaks numpy / matplotlib wheel builds

### ISSUE THREAD

**Issue by matthew-brett** [pypa/auditwheel#68]
Auditwheel 1.6 seems to be failing to detect and graft the dependencies of the wheels.

For new failure example see:  

https://api.travis-ci.org/jobs/227872764/log.txt?deansi=true

For failure fixed by downgrading auditwheel to 1.5:

https://api.travis-ci.org/jobs/227948047/log.txt?deansi=true

With the downgrade, I see this in the log (second link, just above):

```
Grafting: /usr/local/lib/libopenblasp-r0.2.18.so -> numpy/.libs/libopenblasp-r0-39a31c03.2.18.so
Grafting: /usr/lib64/libgfortran.so.3.0.0 -> numpy/.libs/libgfortran-ed201abd.so.3.0.0
Setting RPATH: numpy/core/multiarray.so to "$ORIGIN/../.libs"
Setting RPATH: numpy/linalg/_umath_linalg.so to "$ORIGIN/../.libs"
Setting RPATH: numpy/linalg/lapack_lite.so to "$ORIGIN/../.libs"
```

These are missing in the run with new auditwheel 1.6 (first link above).

Seems to be the same problem for matplotlib:

https://api.travis-ci.org/jobs/227868822/log.txt?deansi=true

Here it looks like the libpng library was not grafted into the matplotlib wheel.

**Comment by rmcgibbo** [comment]
Eek!

**Comment by rmcgibbo** [comment]
(I just see an "Accessed denied" page for the links you posted).

**Comment by rmcgibbo** [comment]
Can you post a link to one of the unfixed wheels that I can use as a testcase?

**Comment by matthew-brett** [comment]
Unfixed : http://nipy.bic.berkeley.edu/wheelhouse/numpy-1.13.0.dev0+43914a4-cp27-cp27mu-linux_x86_64.whl

Fixed (or rather, not fixed, but with auditwheel repair run on it): http://nipy.bic.berkeley.edu/wheelhouse/numpy-1.13.0.dev0+43914a4-cp27-cp27mu-manylinux1_x86_64.whl

**Comment by matthew-brett** [comment]
I tried revising the links - do they work now?

**Comment by rmcgibbo** [comment]
Yep, thanks.

**Comment by rmcgibbo** [comment]
So far: I can reproduce the issue with auditwheel 1.6.0 from pypi. With the master branch in my local directory running `python -m auditwheel` (which should be exactly the same), I can't reproduce. Not yet sure what's going on.

**Comment by rmcgibbo** [comment]
Current status: someone this is related to using pyelftools==0.23 vs pyelftools==0.24.

**Comment by rmcgibbo** [comment]
I think I know what's going on. I'll have a fixed version up on pypi in a couple hours once I have access to my other laptop.

**Comment by sciyoshi** [comment]
auditwheel 1.6 on pypi changed a bunch of strings to binary, ie `'.dynsym'` => `b'.dynsym'`. Was it run through 2to3 or something?

**Comment by rmcgibbo** [comment]
No, it was just the wrong code that  got packaged up.

**Comment by rmcgibbo** [comment]
Someone, I accidently re-release 1.4 as "1.6" on pypi -- I just made tag incorrectly.

**Comment by johnyf** [comment]
Thanks for noting this, it explains [this comment](https://github.com/pypa/auditwheel/issues/67#issuecomment-298257762) (I should have looked at the commit hashes). It seems that deleting tag 1.6 from GitHub will let it show tag 1.5 as the latest release.

A suggestion is to delete the 1.6 release from PyPI, in order to avoid confusion, tag the intended commit as 1.6.1, and release that on PyPI (since PyPI won't allow uploading different content as 1.6).

**Comment by matthew-brett** [comment]
You can also add build tags to the filenames, if you want to stay on 1.6:  https://github.com/MacPython/wiki/wiki/Build-Tags

**Comment by matthew-brett** [comment]
Would you consider doing release candidates and / or some regression tests on example wheel builds to check things are still working, per commit, or before release?

**Comment by sciyoshi** [comment]
FYI - the manylinux docker images will need to be rebuilt once this is fixed, since they pulled in the broken 1.6 version. cc @njsmith

**Comment by rmcgibbo** [comment]
I bumped it to 1.6.1. It should be out now.

**Comment by njsmith** [comment]
https://github.com/pypa/manylinux/pull/110

**Comment by johnyf** [comment]
Thanks for releasing 1.6.1. Release 1.6 is not on PyPI, but the tag is present in the repository https://github.com/pypa/auditwheel/releases/tag/1.6, pointing to 1.4.

**Comment by rmcgibbo** [comment]
Yeah, since 1.6 was broken I deleted it from Pypi after uploading 1.6.1.

**Comment by johnyf** [comment]
Yes, I totally agree, I was just wondering about deleting the tag 1.6 from the repository.

**Comment by njsmith** [comment]
Sounds like this was fixed a while ago.
