### ISSUE TITLE
Commit bit for @ehashman?

### ISSUE THREAD

**Issue by njsmith** [pypa/auditwheel#75]
Hi all,

I'd like to propose @ehashman for a commit bit. See #43, #73 for some previous contributions, and she's interested in getting more involved with auditwheel maintenance.

Any objections? @rmcgibbo?

And mechanically, I think we would need someone with admin rights to the pypa organization to invite her to the manylinux team? @dstufft?

**Comment by rmcgibbo** [comment]
Yeah, would be great. No objections at all. Glad to have you on board!

**Comment by dstufft** [comment]
Invited
