### ISSUE TITLE
Support repairing cffi PyPy extensions

### ISSUE THREAD

**Issue by daa** [pypa/auditwheel#93]
CFFI extensions compiled for PyPy do not export ``'init' + modname`` nor ``'PyInit_' + modname`` symbols but instead they export ``'_cffi_pypyinit_' + modname`` and thus they are skipped by ``auditwheel``. However actually ``auditwheel`` can repair them. As an example one may take a look at ``python-snappy`` - it uses cffi for PyPy. And proof for using ``_cffi_pypyinit_`` prefix may be found at ``cffi/recompiler.py``.

**Comment by njsmith** [comment]
Seems reasonable.
